### ISSUE TITLE
Make the website responsive

### ISSUE THREAD

**Issue by swatified** [07sumit1002/CabRental#174]
Hey I want to make the whole website elements responsive. And add hamburger menu for smaller sizes too. They look broken in various screen sizes: 
![Screenshot 2024-10-04 200321](https://github.com/user-attachments/assets/a37b49cf-d162-49f1-aa62-b8bbfcc048bf)
![Screenshot 2024-10-04 200334](https://github.com/user-attachments/assets/86307345-5e22-40dc-95e2-07516feb2f8a)
![Screenshot 2024-10-04 200513](https://github.com/user-attachments/assets/e65199a7-7bd8-4cfd-8537-2671d85042da)
![Screenshot 2024-10-04 200522](https://github.com/user-attachments/assets/7c5a9149-09d9-4716-95d1-9d8db02c0087)
![Screenshot 2024-10-04 200531](https://github.com/user-attachments/assets/42644d94-3834-422a-8eb7-c59dbd1713dd)
![Screenshot 2024-10-04 200546](https://github.com/user-attachments/assets/8f5037ac-68c0-4524-b64a-6f5bc28d47cb)

**Comment by swatified** [comment]
@07sumit1002 @AniketFirke @amnipriyasowrirajan please assign this to me and add tags of gsssoc-ext, hactoberfest, and level 2 or 3 as you wish. So that i can start working on it asap.

**Comment by amnipriyasowrirajan** [comment]
Hi @swatified,

Thank you for your interest in this task. At the moment, I’m unable to assign it to you directly. However, feel free to start working on it, and you can raise a draft PR when you’re ready.

Looking forward to seeing your contributions!

Best Regards,
Amni

**Comment by AniketFirke** [comment]
Hello Dear,

Thank you for expressing your interest in contributing to this task. At
this moment, I am unable to assign it to you directly. However, you are
welcome to begin working on the task independently. Once you are ready,
please feel free to submit a draft pull request (PR) for review.

We look forward to your contributions and appreciate your initiative.

Best regards,
Mr. Aniket Firke
     Mentor

**Comment by swatified** [comment]
Hey @amnipriyasowrirajan @AniketFirke , I have started working, thank you. I hope you can talk to PA and fix the issue soon. My PR might not get counted in my score otherwise. Hoping to hear back from you soon.

**Comment by AniketFirke** [comment]
It is fixed.

**Comment by swatified** [comment]
when can i expect the tags and assign?

**Comment by AniketFirke** [comment]
It will be done today.

**Comment by swatified** [comment]
Sorry @07sumit1002 that the tags are incorrect. its gssoc-ext and level2 with no space..

**Comment by AniketFirke** [comment]
Fixed!

**Comment by swatified** [comment]
the level2 is still not working but i hope you can fix that and add new tags when i make a pr.

**Comment by AniketFirke** [comment]
Ok, I will try.

**Comment by 07sumit1002** [comment]
@swatified Can you check if it is working now or not

**Comment by AniketFirke** [comment]
Yes, I can see it.

**Comment by AniketFirke** [comment]
Congratulations!
